describe('Test visitando la página, verificando el contenido del sidebar y la consulta de productos', () => {
    it('Probando el contenido que se muestra de manera condicional en el resumen', ()=>{
        cy.visit('/resumen')
        cy.get('p[data-cy=noProductos]').should('have.text', 'No haz agregado productos a tu orden, comienza agregandolos')
        cy.get('button[data-cy=confirmarPedido]').should('not.exist')
    })
    it('agregando un producto al pedido y verificando que se muestre en el resumen', ()=>{
        cy.visit('/')
        cy.get('button[data-cy=botonAgregar]').first().click()
        cy.wait(1000)
        cy.get('button[data-cy=aumentar]').click()
        cy.get('button[data-cy=agregarAlPedido]').click()
        cy.get('a[data-cy=resumen]').click()
        cy.get('button[data-cy=confirmarPedido]').should('exist')
        cy.get('p[data-cy=noProductos]').should('not.exist')
        cy.get('h3[data-cy=productoCarrito]').should('have.text', 'Café Caramel con Chocolate')
        cy.get('p[data-cy=cantidad]').first().should('have.text', 'Cantidad: 1')
        cy.get('p[data-cy=precio]').last().should('have.text', 'Precio: $59.90')
        cy.get('button[data-cy=confirmarPedido]').should('exist') 
        cy.get('button[data-cy=confirmarPedido]').click()
        cy.url().should('include', '/resumen')
        cy.get('input[data-cy=nombre]').type('Juan')
        cy.get('button[data-cy=confirmar]').click()
        cy.get('div[data-cy=alerta]').should('have.class', 'bg-green-600')
        cy.get('p[data-cy=alertaMensaje]').should('have.text', 'Orden creada correctamente')
    })
    it('Comprobando la funcionalidad de editar un producto agregado al pedido', ()=>{
        cy.visit('/')
        cy.get('a[data-cy=Pizzas]').click()
        cy.get('button[data-cy=botonAgregar]').first().click()
        cy.wait(1000)
        cy.get('button[data-cy=aumentar]').click()
        cy.get('button[data-cy=aumentar]').click()
        cy.get('button[data-cy=agregarAlPedido]').click()
        cy.get('a[data-cy=resumen]').click()
        cy.get('button[data-cy=editarProducto]').click()
        cy.get('p[data-cy=cantidad]').should('contain.text', 2)
        cy.get('button[data-cy=disminuir]').click()
        cy.get('p[data-cy=cantidad]').eq(1)
        cy.get('button[data-cy=agregarAlPedido]').should('have.text', 'Guardar Cambios')
        cy.get('button[data-cy=agregarAlPedido]').click()
    })
    it('Comprobando la funcionalidad de eliminar un producto del pedido', ()=>{
        cy.visit('/')
        cy.get('a[data-cy=Pizzas]').click()
        cy.get('button[data-cy=botonAgregar]').first().click()
        cy.wait(1000)
        cy.get('button[data-cy=aumentar]').click()
        cy.get('button[data-cy=aumentar]').click()
        cy.get('button[data-cy=agregarAlPedido]').click()
        cy.get('a[data-cy=resumen]').click()
        cy.get('button[data-cy=eliminarProducto]').click()
        cy.get('div[data-cy=modalConfirmacion]').should('exist')
        cy.get('button[data-cy=botonCancelar]').click()
        cy.get('div[data-cy=modalConfirmacion]').should('not.exist')
        cy.get('button[data-cy=eliminarProducto]').click()
        cy.get('button[data-cy=botonEliminar]').click()
        cy.get('p[data-cy=noProductos]').should('have.text', 'No haz agregado productos a tu orden, comienza agregandolos')
    })
})